// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-news.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/data.ts
var news = [
  { title: "C\xF4ng b\u1ED1 gi\xE1 v\u1EADt li\u1EC7u x\xE2y d\u1EF1ng ngay khi c\xF3 bi\u1EBFn \u0111\u1ED9ng th\u1ECB tr\u01B0\u1EDDng", date: "2026-03-27", category: "C\xF4ng d\xE2n" },
  { title: "C\u1EE5c \u0110\u0103ng ki\u1EC3m t\u01B0\u1EDDng minh nhi\u1EC1u v\u1EA5n \u0111\u1EC1 li\xEAn quan \u0111\u1EBFn quy tr\xECnh ki\u1EC3m tra kh\xED th\u1EA3i v\u1EDBi \u0111\u1ED9ng c\u01A1 diesel", date: "2026-03-27", category: "C\xF4ng d\xE2n" },
  { title: "T\u0103ng m\u1EA1nh m\u1EE9c ph\u1EA1t, si\u1EBFt ch\u1EB7t qu\u1EA3n l\xFD ho\u1EA1t \u0111\u1ED9ng b\u1EE9c x\u1EA1, h\u1EA1t nh\xE2n", date: "2026-03-26", category: "C\xF4ng d\xE2n" },
  { title: "H\u01A1n 12.000 v\u1EADn \u0111\u1ED9ng vi\xEAn tranh t\xE0i t\u1EA1i Gi\u1EA3i v\xF4 \u0111\u1ECBch qu\u1ED1c gia Marathon \u2013 B\xE1o Ti\u1EC1n Phong l\u1EA7n th\u1EE9 67", date: "2026-03-26", category: "Th\u1EC3 thao" },
  { title: "H\u1ED9i ngh\u1ECB tri\u1EC3n khai Ngh\u1ECB quy\u1EBFt v\u1EC1 ph\xE1t tri\u1EC3n kinh t\u1EBF - x\xE3 h\u1ED9i v\xF9ng Duy\xEAn h\u1EA3i Nam Trung B\u1ED9", date: "2026-03-25", category: "Kinh t\u1EBF" },
  { title: "\u0110\u1EA9y nhanh ti\u1EBFn \u0111\u1ED9 thi c\xF4ng c\xE1c tuy\u1EBFn cao t\u1ED1c tr\u1ECDng \u0111i\u1EC3m khu v\u1EF1c mi\u1EC1n Trung", date: "2026-03-25", category: "Giao th\xF4ng" },
  { title: "L\u1ECBch thi t\u1ED1t nghi\u1EC7p THPT n\u0103m 2026", date: "2026-03-25", category: "Gi\xE1o d\u1EE5c" },
  { title: "Kh\xE1nh H\xF2a \u0111\u1EB7t m\u1EE5c ti\xEAu 100% x\xE3, ph\u01B0\u1EDDng, \u0111\u1EB7c khu \u0111\u1EA1t chu\u1EA9n ph\xE1t tri\u1EC3n v\u0103n h\xF3a to\xE0n di\u1EC7n", date: "2026-03-24", category: "V\u0103n h\xF3a" },
  { title: "K\u1EBF ho\u1EA1ch ph\xF2ng b\u1EC7nh phong giai \u0111o\u1EA1n 2026 \u2013 2030", date: "2026-03-24", category: "Y t\u1EBF" },
  { title: "S\u1EEDa quy \u0111\u1ECBnh v\u1EC1 x\u1EED ph\u1EA1t vi ph\u1EA1m h\xE0nh ch\xEDnh l\u0129nh v\u1EF1c kinh doanh b\u1EA3o hi\u1EC3m", date: "2026-03-24", category: "Ch\xEDnh s\xE1ch" },
  { title: "Ch\u1EC9 \u0111\u1EA1o, \u0111i\u1EC1u h\xE0nh c\u1EE7a Ch\xEDnh ph\u1EE7, Th\u1EE7 t\u01B0\u1EDBng Ch\xEDnh ph\u1EE7 n\u1ED5i b\u1EADt tu\u1EA7n t\u1EEB 14\u201320/3/2026", date: "2026-03-24", category: "Ch\xEDnh s\xE1ch" },
  { title: "H\u01B0\u1EDFng \u1EE9ng Ng\xE0y Th\u1EBF gi\u1EDBi ph\xF2ng, ch\u1ED1ng b\u1EC7nh lao 24-3: Ph\xE1t hi\u1EC7n s\u1EDBm \u0111\u1EC3 ti\u1EBFn t\u1EDBi ch\u1EA5m d\u1EE9t b\u1EC7nh lao", date: "2026-03-24", category: "Y t\u1EBF" },
  { title: "Quy ho\u1EA1ch m\u1EA1ng l\u01B0\u1EDBi \u0111\u01B0\u1EDDng s\u1EAFt qu\u1ED1c gia th\u1EDDi k\u1EF3 2021\u20132030, t\u1EA7m nh\xECn \u0111\u1EBFn n\u0103m 2050", date: "2026-03-23", category: "Giao th\xF4ng" },
  { title: "Ph\xEA duy\u1EC7t quy ho\u1EA1ch s\u1EED d\u1EE5ng \u0111\u1EA5t giai \u0111o\u1EA1n 2026\u20132030 tr\xEAn \u0111\u1ECBa b\xE0n t\u1EC9nh", date: "2026-03-22", category: "Quy ho\u1EA1ch" },
  { title: "N\xE2ng cao hi\u1EC7u qu\u1EA3 ph\u1ED1i h\u1EE3p trong tri\u1EC3n khai c\xE1c d\u1EF1 \xE1n \u0111\u1EA7u t\u01B0 x\xE2y d\u1EF1ng", date: "2026-03-21", category: "X\xE2y d\u1EF1ng" },
  { title: "S\u1EEDa \u0111\u1ED5i, b\u1ED5 sung quy \u0111\u1ECBnh v\u1EC1 \u0111\u01A1n gi\xE1 b\u1ED3i th\u01B0\u1EDDng nh\xE0, c\xF4ng tr\xECnh khi Nh\xE0 n\u01B0\u1EDBc thu h\u1ED3i \u0111\u1EA5t", date: "2026-03-20", category: "Ch\xEDnh s\xE1ch" },
  { title: "X\xE2y d\u1EF1ng Kh\xE1nh H\xF2a tr\u1EDF th\xE0nh \u0111i\u1EC3m \u0111\u1EBFn c\u1EE7a c\xE1c s\u1EF1 ki\u1EC7n v\u0103n h\xF3a, ngh\u1EC7 thu\u1EADt v\xE0 gi\u1EA3i tr\xED bi\u1EC3n", date: "2026-03-20", category: "Du l\u1ECBch" }
];
var departments = [
  "V\u0103n ph\xF2ng UBND t\u1EC9nh",
  "S\u1EDF N\u1ED9i v\u1EE5",
  "S\u1EDF T\xE0i ch\xEDnh",
  "S\u1EDF C\xF4ng Th\u01B0\u01A1ng",
  "S\u1EDF N\xF4ng nghi\u1EC7p v\xE0 M\xF4i tr\u01B0\u1EDDng",
  "S\u1EDF D\xE2n t\u1ED9c v\xE0 T\xF4n gi\xE1o",
  "S\u1EDF T\u01B0 ph\xE1p",
  "Thanh tra t\u1EC9nh",
  "S\u1EDF Khoa h\u1ECDc v\xE0 C\xF4ng ngh\u1EC7",
  "S\u1EDF V\u0103n h\xF3a, Th\u1EC3 thao v\xE0 Du l\u1ECBch",
  "S\u1EDF X\xE2y d\u1EF1ng",
  "S\u1EDF Gi\xE1o d\u1EE5c v\xE0 \u0110\xE0o t\u1EA1o",
  "S\u1EDF Y t\u1EBF",
  "S\u1EDF Ngo\u1EA1i v\u1EE5",
  "Ban Qu\u1EA3n l\xFD Khu kinh t\u1EBF v\xE0 Khu c\xF4ng nghi\u1EC7p",
  "Ban Qu\u1EA3n l\xFD V\u01B0\u1EDDn QG N\xFAi Ch\xFAa \u2013 Ph\u01B0\u1EDBc B\xECnh",
  "Ban qu\u1EA3n l\xFD d\u1EF1 \xE1n ph\xE1t tri\u1EC3n t\u1EC9nh",
  "Ban Qu\u1EA3n l\xFD d\u1EF1 \xE1n \u0111\u1EA7u t\u01B0 x\xE2y d\u1EF1ng",
  "Ban QLDA \u0111\u1EA7u t\u01B0 x\xE2y d\u1EF1ng c\xE1c c\xF4ng tr\xECnh N\xF4ng nghi\u1EC7p v\xE0 Giao th\xF4ng"
];
var localities = [
  "TP. Nha Trang",
  "TP. Cam Ranh",
  "TX. Ninh H\xF2a",
  "Huy\u1EC7n Di\xEAn Kh\xE1nh",
  "Huy\u1EC7n Cam L\xE2m",
  "Huy\u1EC7n V\u1EA1n Ninh",
  "Huy\u1EC7n Kh\xE1nh S\u01A1n",
  "Huy\u1EC7n Kh\xE1nh V\u0129nh",
  "\u0110\u1EB7c khu B\u1EAFc V\xE2n Phong",
  "\u0110\u1EB7c khu Tr\u01B0\u1EDDng Sa"
];
var contact = {
  organization: "C\u1ED5ng Th\xF4ng tin \u0111i\u1EC7n t\u1EED t\u1EC9nh Kh\xE1nh H\xF2a",
  managedBy: "V\u0103n ph\xF2ng UBND t\u1EC9nh Kh\xE1nh H\xF2a",
  address: "01 Tr\u1EA7n Ph\xFA, ph\u01B0\u1EDDng L\u1ED9c Th\u1ECD, th\xE0nh ph\u1ED1 Nha Trang, t\u1EC9nh Kh\xE1nh H\xF2a",
  phones: ["(0258) 3.822.500", "(0258) 3.827.008"],
  email: "congttdt@khanhhoa.gov.vn",
  website: "www.khanhhoa.gov.vn",
  editorInChief: "Ch\xE1nh V\u0103n ph\xF2ng UBND t\u1EC9nh"
};

// src/lib/mcp/tools/list-news.ts
var list_news_default = defineTool({
  name: "list_news",
  title: "List portal news",
  description: "List recent news and announcements published on the Kh\xE1nh H\xF2a provincial portal, optionally filtered by category or a keyword in the title.",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter, e.g. 'Y t\u1EBF', 'Giao th\xF4ng', 'Ch\xEDnh s\xE1ch'."),
    query: z.string().optional().describe("Optional keyword to match against the article title."),
    limit: z.number().int().optional().describe("Maximum number of articles to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, query, limit }) => {
    const max = Math.min(Math.max(limit ?? 10, 1), 50);
    const q = query?.trim().toLowerCase();
    const cat = category?.trim().toLowerCase();
    const items = news.filter((n) => cat ? n.category.toLowerCase().includes(cat) : true).filter((n) => q ? n.title.toLowerCase().includes(q) : true).slice(0, max);
    return {
      content: [
        {
          type: "text",
          text: items.length ? items.map((n) => `${n.date} [${n.category}] ${n.title}`).join("\n") : "No matching articles were found."
        }
      ],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/tools/list-organizations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_organizations_default = defineTool2({
  name: "list_organizations",
  title: "List departments and localities",
  description: "List the provincial departments/agencies (s\u1EDF, ban, ng\xE0nh) and the local administrative units (x\xE3, ph\u01B0\u1EDDng, \u0111\u1EB7c khu) of Kh\xE1nh H\xF2a province.",
  inputSchema: {
    kind: z2.enum(["departments", "localities", "all"]).optional().describe("Which set to return: departments, localities, or all (default).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ kind }) => {
    const which = kind ?? "all";
    const result = {};
    if (which === "departments" || which === "all") result.departments = departments;
    if (which === "localities" || which === "all") result.localities = localities;
    const lines = [];
    if (result.departments) lines.push("S\u1EDF, ban, ng\xE0nh:", ...result.departments.map((d) => `- ${d}`));
    if (result.localities) lines.push("\u0110\u1ECBa ph\u01B0\u01A1ng:", ...result.localities.map((l) => `- ${l}`));
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get portal contact info",
  description: "Get the official contact details of the Kh\xE1nh H\xF2a provincial portal: address, phone numbers, email, managing office and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          contact.organization,
          `C\u01A1 quan qu\u1EA3n l\xFD: ${contact.managedBy}`,
          `\u0110\u1ECBa ch\u1EC9: ${contact.address}`,
          `\u0110i\u1EC7n tho\u1EA1i: ${contact.phones.join(" / ")}`,
          `Email: ${contact.email}`,
          `Website: ${contact.website}`,
          `Tr\u01B0\u1EDFng Ban bi\xEAn t\u1EADp: ${contact.editorInChief}`
        ].join("\n")
      }
    ],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var projectRef = "mhqnbfauxmmrglgfdwex";
var mcp_default = defineMcp({
  name: "pixel-perfect-replica",
  title: "Pixel Perfect Replica",
  version: "0.1.0",
  instructions: "Tools for the Kh\xE1nh H\xF2a provincial e-government portal. Use `list_news` for recent articles and announcements, `list_organizations` for departments and localities, and `get_contact_info` for official contact details.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_news_default, list_organizations_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
